package cr.kaytes.modelo;
// Generated Mar 25, 2018 5:41:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name="ARTICULO"
    ,schema="ADMIN"
)
public class Articulo  implements java.io.Serializable {


     private int pkIdarticulo;
     private Marca marca;
     private Producto producto;
     private int codigo;
     private String talla;
     private String genero;
     private String color;
     private BigDecimal precio;
     private String estado;

    public Articulo() {
    }

	
    public Articulo(int pkIdarticulo, Marca marca, Producto producto, int codigo, String color, BigDecimal precio, String estado) {
        this.pkIdarticulo = pkIdarticulo;
        this.marca = marca;
        this.producto = producto;
        this.codigo = codigo;
        this.color = color;
        this.precio = precio;
        this.estado = estado;
    }
    public Articulo(int pkIdarticulo, Marca marca, Producto producto, int codigo, String talla, String genero, String color, BigDecimal precio, String estado) {
       this.pkIdarticulo = pkIdarticulo;
       this.marca = marca;
       this.producto = producto;
       this.codigo = codigo;
       this.talla = talla;
       this.genero = genero;
       this.color = color;
       this.precio = precio;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="PK_IDARTICULO", unique=true, nullable=false, precision=5, scale=0)
    public int getPkIdarticulo() {
        return this.pkIdarticulo;
    }
    
    public void setPkIdarticulo(int pkIdarticulo) {
        this.pkIdarticulo = pkIdarticulo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_IDMARCA", nullable=false)
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_IDPRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="CODIGO", nullable=false, precision=5, scale=0)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="TALLA", length=2)
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }

    
    @Column(name="GENERO", length=15)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="COLOR", nullable=false, length=8)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="PRECIO", nullable=false, precision=6, scale=4)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="ESTADO", nullable=false, length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


