package cr.kaytes.modelo;
// Generated 26/03/2018 02:34:33 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name="ARTICULO"
    ,schema="ADMIN"
)
public class Articulo  implements java.io.Serializable {


     private int pkIdarticulo;
     private int  producto;
     private int  marca;
     private int codigo;
     private String talla;
     private String genero;
     private String color;
     private double precio;
     private String estado;

    public Articulo() {
    }

	
    public Articulo(int  producto, int  marca, int codigo, String color, double precio, String estado) {
        this.producto = producto;
        this.marca = marca;
        this.codigo = codigo;
        this.color = color;
        this.precio = precio;
        this.estado = estado;
    }
    public Articulo(int  producto, int  marca, int codigo, String talla, String genero, String color, double precio, String estado) {
       this.producto = producto;
       this.marca = marca;
       this.codigo = codigo;
       this.talla = talla;
       this.genero = genero;
       this.color = color;
       this.precio = precio;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="PK_IDARTICULO", unique=true, nullable=false, precision=5, scale=0)
    public int getPkIdarticulo() {
        return this.pkIdarticulo;
    }
    
    public void setPkIdarticulo(int pkIdarticulo) {
        this.pkIdarticulo = pkIdarticulo;
    }


    @Column(name="FK_IDPRODUCTO", nullable=false)
    public int  getProducto() {
        return this.producto;
    }
    
    public void setProducto(int  producto) {
        this.producto = producto;
    }


    @Column(name="FK_IDMARCA", nullable=false)
    public int  getMarca() {
        return this.marca;
    }
    
    public void setMarca(int  marca) {
        this.marca = marca;
    }

    
    @Column(name="CODIGO", nullable=false, precision=5, scale=0)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="TALLA", length=2)
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }

    
    @Column(name="GENERO", length=15)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="COLOR", nullable=false, length=8)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="PRECIO", nullable=false, precision=126, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

    
    @Column(name="ESTADO", nullable=false, length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


