package cr.kaytes.modelo;
// Generated 26/03/2018 02:34:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="PRODUCTO"
    ,schema="ADMIN"
    , uniqueConstraints = @UniqueConstraint(columnNames="TIPO_PRODUCTO") 
)
public class Producto  implements java.io.Serializable {


     private int pkIdproducto;
     private String tipoProducto;
     private Set<Articulo> articulos = new HashSet<Articulo>(0);

    public Producto() {
    }

	
    public Producto(String tipoProducto) {
        this.pkIdproducto = pkIdproducto;
        this.tipoProducto = tipoProducto;
    }
    public Producto(String tipoProducto, Set<Articulo> articulos) {
       this.pkIdproducto = pkIdproducto;
       this.tipoProducto = tipoProducto;
       this.articulos = articulos;
    }
   
     @Id 

    
    @Column(name="PK_IDPRODUCTO", unique=true, nullable=false, precision=5, scale=0)
    public int getPkIdproducto() {
        return this.pkIdproducto;
    }
    
    public void setPkIdproducto(int pkIdproducto) {
        this.pkIdproducto = pkIdproducto;
    }

    
    @Column(name="TIPO_PRODUCTO", unique=true, nullable=false, length=10)
    public String getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(String tipoProducto) {
        this.tipoProducto = tipoProducto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<Articulo> getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set<Articulo> articulos) {
        this.articulos = articulos;
    }




}


