package cr.kaytes.modelo;
// Generated 26/03/2018 02:34:33 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="ADMIN"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOMBRE_USUARIO") 
)
public class Usuario  implements java.io.Serializable {


     private int pkIdusuario;
     private String nombreUsuario;
     private String password;

    public Usuario() {
    }

    public Usuario(String nombreUsuario, String password) {
       this.pkIdusuario = pkIdusuario;
       this.nombreUsuario = nombreUsuario;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="PK_IDUSUARIO", unique=true, nullable=false, precision=5, scale=0)
    public int getPkIdusuario() {
        return this.pkIdusuario;
    }
    
    public void setPkIdusuario(int pkIdusuario) {
        this.pkIdusuario = pkIdusuario;
    }

    
    @Column(name="NOMBRE_USUARIO", unique=true, nullable=false, length=15)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="PASSWORD", nullable=false, length=8)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


